on:
  push:
    branches:
    - main
  pull_request:
    branches:
    - main
name: Lint
env:
  GOPRIVATE: "github.com/meow-io"
  GH_ACCESS_TOKEN: ${{ secrets.GH_ACCESS_TOKEN }}

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/setup-go@v3
      with:
        go-version: 1.20.x
    - uses: actions/checkout@v3
    - name: Configure git to use ssh
      run: git config --global url."https://joshbuddy:${GH_ACCESS_TOKEN}@github.com/".insteadOf "https://github.com/"
    - run: go install golang.org/x/vuln/cmd/govulncheck@latest
    - name: golangci-lint
      uses: golangci/golangci-lint-action@v2
      with:
        skip-go-installation: true
        version: latest
        args: --timeout 3m --verbose
