on:
  push:
    branches:
    - main
  pull_request:
    branches:
    - main
name: Test
env:
  GOPRIVATE: "github.com/meow-io"
  GH_ACCESS_TOKEN: ${{ secrets.GH_ACCESS_TOKEN }}

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/setup-go@v3
      with:
        go-version: 1.20.x
    - uses: actions/checkout@v3
    - name: Configure git to use ssh
      run: git config --global url."https://joshbuddy:${GH_ACCESS_TOKEN}@github.com/".insteadOf "https://github.com/"
    - run: ./scripts/test
